# Apoie a traducao Biblica Belem An.C 2025
# https://aculpaedasovelhas.org/colabore.html

github: [AndersonOtimiza]
custom:
  - https://aculpaedasovelhas.org/colabore.html
  - https://pix.aculpaedasovelhas.org
